name: l-smash
kind: native
enabled: true
tier: 0
tags: [codec]
sources:
  - file: l-smash-2.14.5.tar.gz
    urls:
      - https://github.com/l-smash/l-smash/archive/v2.14.5.tar.gz
      - pmbs:l-smash/l-smash-2.14.5.tar.gz
      - mirror-src:l-smash
    sha256: e6f7c31de684f4b89ee27e5cd6262bf96f2a5b117ba938d2d606cf6220f05935
    size: 465037
