name: build-publish

on:
  workflow_dispatch:
  schedule:
    - cron: '17 19 * * *'

permissions:
  contents: read

concurrency:
  group: packman-nova-tumbleweed-x86_64
  cancel-in-progress: false

jobs:
  build-publish:
    runs-on: ubuntu-26.04
    timeout-minutes: 350
    env:
      PACKMAN_NOVA_WORKDIR: ${{ github.workspace }}/../workdir
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: sudo apt-get update -qq && sudo apt-get install -y -qq podman zstd
      - run: echo "${{ secrets.PACKMAN_NOVA_DOTENV }}" > .env
      - run: bundle exec exe/packman-nova image build
      - run: bundle exec exe/packman-nova state pull --allow-missing
      - id: run
        run: bundle exec exe/packman-nova run --provider s3
      - if: always() && steps.run.outcome != 'skipped'
        run: bundle exec exe/packman-nova state push
